# Generated by Django 3.2 on 2021-05-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='barang',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laporan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prodi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
